/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 14
#define YY_END_OF_BUFFER 15
static yyconst short int yy_accept[263] =
    {   0,
        0,    0,   15,   14,    8,    9,   10,   10,   11,   11,
       11,   13,   11,    5,    5,   14,   11,   11,   11,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,   10,   11,    8,
        0,    7,    0,    0,    5,    5,   12,   11,    6,    0,
        6,    5,   11,    0,    0,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    4,    4,    4,    4,    1,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    3,    4,    4,    4,    4,    0,    5,   12,    6,
        0,    0,    4,    4,    4,    4,    4,    4,    4,    3,

        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    0,    0,    0,    4,    4,    4,    3,    4,
        0,    4,    4,    4,    4,    3,    0,    0,    0,    0,
        4,    4,    4,    4,    0,    4,    4,    4,    4,    4,
        1,    4,    4,    4,    4,    4,    0,    0,    4,    4,
        0,    4,    4,    4,    0,    0,    0,    0,    0,    0,
        0,    0,    4,    4,    4,    0,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    0,    0,    4,    1,
        0,    4,    4,    0,    2,    0,    0,    0,    0,    0,
        0,    4,    0,    4,    4,    4,    4,    4,    0,    0,

        4,    0,    4,    4,    0,    0,    0,    0,    0,    0,
        0,    4,    1,    4,    0,    0,    4,    3,    4,    0,
        0,    0,    0,    0,    4,    4,    0,    0,    4,    0,
        0,    0,    0,    0,    4,    0,    0,    4,    0,    0,
        0,    0,    4,    0,    0,    4,    0,    0,    0,    1,
        1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    6,    7,
        8,    9,   10,    1,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,   17,
       18,   19,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   25,   25,   29,   25,   30,   31,   25,
       25,   32,   33,   34,   35,   36,   25,   25,   37,   25,
       38,   39,   40,   41,   42,    1,   43,   25,   44,   45,

       46,   47,   48,   49,   50,   25,   25,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       25,   25,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[68] =
    {   0,
        1,    2,    3,    2,    1,    1,    4,    1,    1,    1,
        1,    1,    1,    5,    5,    6,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    1,    1,
        1,    5,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[269] =
    {   0,
        0,    0,  520,  972,   66,  972,   64,  972,  972,   59,
       64,   68,   59,   72,   76,  498,  492,  972,  489,   90,
       91,   97,   98,  104,  108,  112,  116,  120,  129,  135,
      136,  143,  153,  170,  174,  189,  196,  494,  972,  105,
       91,  972,  500,  111,  134,  180,    0,  972,  120,  139,
      187,  193,  972,  207,  163,  211,  215,  222,  226,  230,
      234,  241,  242,  249,  255,  256,  262,  263,  269,  273,
      279,  283,  289,  293,  297,  304,  365,  310,  327,  314,
      318,  331,  342,  353,  338,  354,  485,  336,    0,  165,
      181,  223,  386,  410,  387,  406,  416,  417,  431,  435,

      442,  446,  450,  456,  460,  466,  473,  477,  483,  487,
      494,  498,  440,  507,  398,  511,  515,  519,  523,  527,
      535,  541,  542,  548,  549,  555,  423,  424,  443,  563,
      568,  575,  586,  590,  596,  602,  603,  609,  613,  617,
      621,  625,  629,  633,  639,  645,  440,  649,  652,  656,
      432,  662,  666,  673,  690,  322,  440,  438,  438,  426,
      431,  407,  674,  683,  697,  387,  684,  701,  713,  724,
      728,  732,  736,  742,  746,  750,  365,  717,  758,  759,
      367,  765,  766,  474,  972,  390,  384,  389,  373,  381,
      364,  778,  349,  779,  785,  795,  799,  803,  350,  809,

      810,  339,  814,  820,  360,  350,  336,  339,  314,  311,
      283,  826,  834,  838,  272,  845,  852,  972,  853,  282,
      286,  287,  277,  272,  861,  867,  239,  860,  868,  258,
      259,  256,  250,  242,  875,  208,  879,  882,  231,  217,
      206,  203,  886,  185,  876,  898,  179,  197,  188,  972,
      904,  155,  133,  124,  113,   94,   88,   96,   79,   60,
       61,  972,  944,  949,  954,   79,  960,  965
    } ;

static yyconst short int yy_def[269] =
    {   0,
      262,    1,  262,  262,  262,  262,  263,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  262,  262,  262,
      263,  262,  263,  262,  262,  262,  265,  262,  262,  262,
      262,  262,  262,  262,  266,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  267,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  262,  262,  265,  262,
      266,  268,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  262,  262,  266,  264,  264,  264,  264,  264,
      262,  264,  264,  264,  264,  264,  262,  262,  268,  262,
      264,  264,  264,  264,  262,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  262,  268,  264,  264,
      262,  264,  264,  264,  262,  262,  262,  262,  262,  262,
      262,  262,  264,  264,  264,  262,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  262,  268,  264,  264,
      262,  264,  264,  262,  262,  262,  262,  262,  262,  262,
      262,  264,  262,  264,  264,  264,  264,  264,  262,  268,

      264,  262,  264,  264,  262,  262,  262,  262,  262,  262,
      262,  264,  264,  264,  262,  268,  264,  262,  264,  262,
      262,  262,  262,  262,  264,  264,  262,  268,  264,  262,
      262,  262,  262,  262,  264,  262,  268,  264,  262,  262,
      262,  262,  264,  262,  268,  264,  262,  262,  262,  262,
      268,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,    0,  262,  262,  262,  262,  262,  262
    } ;

static yyconst short int yy_nxt[1040] =
    {   0,
        4,    5,    6,    5,    7,    8,    8,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   21,   20,   20,   20,   20,   20,   20,   20,   22,
       20,   23,   20,   20,   20,   24,   20,    8,   18,    8,
       18,    4,   25,   26,   27,   28,   29,   20,   20,   30,
       31,   20,   32,   33,   20,   20,   34,   20,   35,   36,
       20,   20,   37,    8,   38,    8,   39,   40,   42,   40,
       44,   48,   45,   46,   47,   44,   48,   45,   46,   48,
       92,   49,   49,   50,  156,   51,   51,   50,  261,   52,
       52,   54,   54,   54,   54,   42,   55,   55,   54,   54,

       54,   54,   43,   55,   55,   54,   40,   54,   40,   54,
       55,   54,  156,   54,   55,   54,  260,   54,   55,   54,
      259,   54,   55,   54,   49,   49,   55,   58,  258,   43,
       54,   59,   54,   49,   49,   55,   54,   54,   54,   54,
      257,   55,   55,   60,   54,   50,   54,   51,   51,   55,
       57,   62,   90,   90,   54,  156,   54,   61,   63,   55,
       64,   69,   67,  256,   91,   65,   91,   66,   68,   70,
       71,   54,   72,   54,   73,   54,   55,   54,   90,   90,
       55,   70,   91,  255,   91,   74,   75,   76,   77,   78,
       54,   50,   54,   88,   88,   55,   79,   54,   50,   54,

       51,   51,   55,   80,   50,   81,   52,   52,   54,   82,
       54,  254,   54,   55,   54,   83,   54,   55,   54,  253,
      252,   55,   84,   54,  128,   54,  128,   54,   55,   54,
      250,   54,   55,   54,  156,   54,   55,   54,  130,  249,
       55,   85,   54,   54,   54,   54,  248,   55,   55,   86,
       54,   94,   54,  247,   95,   55,   54,   54,   54,   54,
      244,   55,   55,   54,   54,   54,   54,  156,   55,   55,
       54,   93,   54,  242,   54,   55,   54,  241,  240,   55,
       54,  239,   54,   97,   54,   55,   54,   96,  236,   55,
       54,   99,   54,  100,   54,   55,   54,   98,   54,   55,

       54,  234,  233,   55,  103,   54,  232,   54,  104,  231,
       55,   54,  101,   54,  102,   54,   55,   54,  230,   54,
       55,   54,  227,  184,   55,  184,  105,   70,   54,  185,
       54,  108,   54,   55,  121,  218,  106,   55,  224,   54,
      107,   54,  156,   54,   55,   54,  109,   50,   55,   88,
       88,  110,  111,  117,   54,   54,   54,   54,   70,   55,
       55,  120,  223,  118,  112,  113,  114,  222,  114,  113,
      113,  115,  113,  113,  113,  113,  113,  113,  221,  220,
      113,  113,  113,  113,  218,  119,  122,   54,   54,   54,
       54,  215,   55,   55,  211,  210,  125,  123,  124,   91,

      209,   91,  113,  113,  113,  113,  208,   54,  207,   54,
      126,   54,   55,   54,  206,   70,   55,   54,   54,   54,
       54,  205,   55,   55,  202,  128,  199,  128,  113,  113,
      113,  113,   54,   70,   54,  193,   54,   55,  135,  130,
      191,   55,  131,   54,  128,   54,  128,   54,   55,   54,
      148,   54,   55,   54,  190,  189,   55,   54,  130,   54,
       70,   54,   55,   54,  188,  132,   55,   54,  187,   54,
      133,  186,   55,  134,   54,  184,   54,  184,   54,   55,
       54,  185,  181,   55,   54,  177,   54,   48,   54,   55,
       54,  136,  147,   55,  137,   54,  127,   54,  139,   54,

       55,   54,  262,  140,   55,   87,   53,  138,   54,   53,
       54,  141,   54,   55,   54,   48,   54,   55,   54,  262,
       54,   55,   54,  262,   54,   55,   54,  262,   54,   55,
       54,  262,  142,   55,   70,  143,   54,  144,   54,  145,
      146,   55,   54,   54,   54,   54,  262,   55,   55,   54,
       54,   54,   54,  262,   55,   55,   54,  150,   54,  147,
      262,   55,  262,  149,  155,  156,  155,  262,   70,   54,
      262,   54,   70,   70,   55,  262,   54,  262,   54,  262,
      151,   55,  157,  158,  159,  262,  152,   54,  262,   54,
      160,   54,   55,   54,  161,  162,   55,   54,  154,   54,

       70,  153,   55,   54,   54,   54,   54,  262,   55,   55,
       54,  262,   54,  163,   54,   55,   54,  262,   54,   55,
       54,  262,   54,   55,   54,  164,   54,   55,   54,  262,
       54,   55,   54,  262,   54,   55,   54,  262,  262,   55,
       54,  262,   54,  165,  262,   55,   54,   70,   54,  167,
      128,   55,  128,   54,  166,   54,  168,   54,   55,   54,
      262,  262,   55,   54,  130,   54,   70,   54,   55,   54,
      171,  169,   55,  170,   54,   54,   54,   54,  262,   55,
       55,  172,  174,  262,   54,   54,   54,   54,  173,   55,
       55,  155,  156,  155,  178,  175,  262,  179,   54,  262,

       54,  176,   54,   55,   54,  262,  180,   55,  182,  157,
      158,  159,  262,  262,   54,  183,   54,  160,  128,   55,
      128,  161,  162,   70,  262,   54,  192,   54,  262,   54,
       55,   54,  130,   54,   55,   54,   70,   54,   55,   54,
      262,   70,   55,   54,  262,   54,  262,   54,   55,   54,
      262,   54,   55,   54,   70,  262,   55,   70,  180,   54,
       54,   54,   54,  262,   55,   55,   54,   54,   54,   54,
      262,   55,   55,  194,   70,  262,  262,   70,  200,   54,
       54,   54,   54,  262,   55,   55,   54,  196,   54,  262,
      262,   55,  195,  262,  262,  197,   54,  262,   54,  198,

       54,   55,   54,  262,   54,   55,   54,  262,  262,   55,
      128,   54,  128,   54,  203,   54,   55,   54,  262,  201,
       55,   54,  204,   54,  130,  262,   55,   54,  262,   54,
       70,  262,   55,  212,  262,   54,   70,   54,  262,   54,
       55,   54,  262,  262,   55,  214,  128,  262,  128,  262,
      216,  217,  213,   54,   54,   54,   54,   70,   55,   55,
      130,  128,   54,  128,   54,   70,  219,   55,   54,   54,
       54,   54,  262,   55,   55,  130,   54,  128,   54,  128,
      128,   55,  128,   54,  225,   54,  262,   54,   55,   54,
      226,  130,   55,  262,  130,  228,  262,  262,   70,   54,

      262,   54,  229,  262,   55,  128,  262,  128,  262,  237,
      235,  262,  262,  262,  262,  262,  262,  238,  262,  130,
      262,  251,  262,  262,  262,   70,  262,  262,  243,  262,
      262,  245,  262,  262,  246,  262,  262,  262,   70,  262,
      262,  262,  262,   70,   41,   41,   41,   41,   41,   41,
       56,  262,   56,   56,   89,   89,  262,   89,   89,   89,
      116,  116,  262,  116,  116,  116,  129,  262,  262,  129,
      129,    3,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262
    } ;

static yyconst short int yy_chk[1040] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    7,    5,
       10,   13,   10,   10,   11,   11,   13,   11,   11,   12,
      266,   12,   12,   14,  261,   14,   14,   15,  260,   15,
       15,   20,   21,   20,   21,   41,   20,   21,   22,   23,

       22,   23,    7,   22,   23,   24,   40,   24,   40,   25,
       24,   25,  259,   26,   25,   26,  258,   27,   26,   27,
      257,   28,   27,   28,   44,   44,   28,   22,  256,   41,
       29,   22,   29,   49,   49,   29,   30,   31,   30,   31,
      255,   30,   31,   23,   32,   45,   32,   45,   45,   32,
       21,   25,   50,   50,   33,  254,   33,   24,   25,   33,
       25,   27,   26,  253,   55,   25,   55,   25,   26,   27,
       28,   34,   28,   34,   29,   35,   34,   35,   90,   90,
       35,   30,   91,  252,   91,   29,   30,   30,   30,   31,
       36,   46,   36,   46,   46,   36,   32,   37,   51,   37,

       51,   51,   37,   33,   52,   33,   52,   52,   54,   33,
       54,  249,   56,   54,   56,   34,   57,   56,   57,  248,
      247,   57,   35,   58,   92,   58,   92,   59,   58,   59,
      244,   60,   59,   60,  242,   61,   60,   61,   92,  241,
       61,   36,   62,   63,   62,   63,  240,   62,   63,   37,
       64,   58,   64,  239,   59,   64,   65,   66,   65,   66,
      236,   65,   66,   67,   68,   67,   68,  234,   67,   68,
       69,   57,   69,  233,   70,   69,   70,  232,  231,   70,
       71,  230,   71,   61,   72,   71,   72,   60,  227,   72,
       73,   63,   73,   64,   74,   73,   74,   62,   75,   74,

       75,  224,  223,   75,   67,   76,  222,   76,   68,  221,
       76,   78,   65,   78,   66,   80,   78,   80,  220,   81,
       80,   81,  215,  156,   81,  156,   69,   72,   79,  156,
       79,   73,   82,   79,   82,  211,   71,   82,  210,   85,
       72,   85,  209,   83,   85,   83,   74,   88,   83,   88,
       88,   75,   76,   78,   84,   86,   84,   86,   80,   84,
       86,   81,  208,   78,   76,   77,   77,  207,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,  206,  205,
       77,   77,   77,   77,  202,   79,   83,   93,   95,   93,
       95,  199,   93,   95,  193,  191,   85,   83,   84,  115,

      190,  115,   77,   77,   77,   77,  189,   96,  188,   96,
       86,   94,   96,   94,  187,   95,   94,   97,   98,   97,
       98,  186,   97,   98,  181,  128,  177,  128,   77,   77,
       77,   77,   99,   94,   99,  166,  100,   99,  100,  128,
      162,  100,   93,  101,  129,  101,  129,  102,  101,  102,
      115,  103,  102,  103,  161,  160,  103,  104,  129,  104,
       97,  105,  104,  105,  159,   96,  105,  106,  158,  106,
       98,  157,  106,   99,  107,  184,  107,  184,  108,  107,
      108,  184,  151,  108,  109,  147,  109,  127,  110,  109,
      110,  101,  113,  110,  102,  111,   87,  111,  104,  112,

      111,  112,   43,  105,  112,   38,   19,  103,  114,   17,
      114,  106,  116,  114,  116,   16,  117,  116,  117,    3,
      118,  117,  118,    0,  119,  118,  119,    0,  120,  119,
      120,    0,  107,  120,  109,  108,  121,  110,  121,  111,
      112,  121,  122,  123,  122,  123,    0,  122,  123,  124,
      125,  124,  125,    0,  124,  125,  126,  117,  126,  114,
        0,  126,    0,  116,  130,  130,  130,    0,  119,  131,
        0,  131,  120,  118,  131,    0,  132,    0,  132,    0,
      121,  132,  130,  130,  130,    0,  122,  133,    0,  133,
      130,  134,  133,  134,  130,  130,  134,  135,  125,  135,

      124,  123,  135,  136,  137,  136,  137,    0,  136,  137,
      138,    0,  138,  131,  139,  138,  139,    0,  140,  139,
      140,    0,  141,  140,  141,  132,  142,  141,  142,    0,
      143,  142,  143,    0,  144,  143,  144,    0,    0,  144,
      145,    0,  145,  133,    0,  145,  146,  134,  146,  136,
      148,  146,  148,  149,  135,  149,  137,  150,  149,  150,
        0,    0,  150,  152,  148,  152,  138,  153,  152,  153,
      141,  139,  153,  140,  154,  163,  154,  163,    0,  154,
      163,  142,  144,    0,  164,  167,  164,  167,  143,  164,
      167,  155,  155,  155,  148,  145,    0,  149,  165,    0,

      165,  146,  168,  165,  168,    0,  150,  168,  152,  155,
      155,  155,    0,    0,  169,  153,  169,  155,  178,  169,
      178,  155,  155,  154,    0,  170,  163,  170,    0,  171,
      170,  171,  178,  172,  171,  172,  167,  173,  172,  173,
        0,  164,  173,  174,    0,  174,    0,  175,  174,  175,
        0,  176,  175,  176,  165,    0,  176,  168,  169,  179,
      180,  179,  180,    0,  179,  180,  182,  183,  182,  183,
        0,  182,  183,  170,  171,    0,    0,  172,  178,  192,
      194,  192,  194,    0,  192,  194,  195,  174,  195,    0,
        0,  195,  173,    0,    0,  175,  196,    0,  196,  176,

      197,  196,  197,    0,  198,  197,  198,    0,    0,  198,
      200,  201,  200,  201,  182,  203,  201,  203,    0,  179,
      203,  204,  183,  204,  200,    0,  204,  212,    0,  212,
      195,    0,  212,  194,    0,  213,  192,  213,    0,  214,
      213,  214,    0,    0,  214,  198,  216,    0,  216,    0,
      200,  201,  196,  217,  219,  217,  219,  197,  217,  219,
      216,  228,  225,  228,  225,  204,  203,  225,  226,  229,
      226,  229,    0,  226,  229,  228,  235,  245,  235,  245,
      237,  235,  237,  238,  212,  238,    0,  243,  238,  243,
      214,  245,  243,    0,  237,  216,    0,    0,  219,  246,

        0,  246,  217,    0,  246,  251,    0,  251,    0,  228,
      225,    0,    0,    0,    0,    0,    0,  229,    0,  251,
        0,  245,    0,    0,    0,  226,    0,    0,  235,    0,
        0,  237,    0,    0,  238,    0,    0,    0,  243,    0,
        0,    0,    0,  246,  263,  263,  263,  263,  263,  263,
      264,    0,  264,  264,  265,  265,    0,  265,  265,  265,
      267,  267,    0,  267,  267,  267,  268,    0,    0,  268,
      268,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "example1.l"
#define INITIAL 0
#line 3 "example1.l"
	#include<stdio.h>
	int line=1, col=1;
#line 685 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 30 "example1.l"

#line 838 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 263 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 972 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 31 "example1.l"
{
					printf(" %s %s ", " Keyword", yytext);
					col += yyleng;
				}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "example1.l"
{
					printf(" %s %s ", "Function", yytext);
					col += yyleng;
				}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "example1.l"
{
					printf(" %s %s ", "Special Operator", yytext);
					col += yyleng;
				}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "example1.l"
{
					printf(" %s %s ", "Identifier", yytext);
					col += yyleng;
				}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 47 "example1.l"
{
					printf(" %s %s ", "Integer", yytext);
					col += yyleng;
				}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "example1.l"
{
					printf(" %s %s ", "Real", yytext);
					col += yyleng;
				}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 55 "example1.l"
{
					printf(" %s %s ", "String", yytext);
					col += yyleng;
				}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 59 "example1.l"
{
					/*printf(" %s %s ", "WhiteSpace", yytext);*/
					col += yyleng;
				}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 63 "example1.l"
{
					/*printf(" %s %s ", "NewLine", yytext);*/
					printf("\n");
					line++;
					col=1;	
				}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 69 "example1.l"
{
					printf(" %s %s ", "Delimiter", yytext);
					col += yyleng;
				}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "example1.l"
{
					printf(" %s %s ", "Operator", yytext);
					col += yyleng;
				}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 77 "example1.l"
{
					printf(" %s %s ", "Comment", yytext);
					col += yyleng;
				}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 81 "example1.l"
{
					printf(" %s %s ", "Dot", yytext);
				}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 84 "example1.l"
ECHO;
	YY_BREAK
#line 1031 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 263 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 263 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 262);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 84 "example1.l"


int main() {
	yylex();
	return 0;
}