/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 16
#define YY_END_OF_BUFFER 17
static yyconst short int yy_accept[334] =
    {   0,
        0,    0,   17,   16,    9,   10,   11,   11,   12,   12,
       12,   14,   12,    6,    6,   15,   12,   12,   12,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,   11,   12,    9,    0,    8,    0,    0,    6,
        6,   13,   12,    7,    0,    7,    6,   12,    0,    0,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    5,    5,    5,    5,
        5,    1,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    4,    5,    5,    5,

        5,    5,    0,    6,   13,    7,    0,    0,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    0,    0,    0,    5,
        5,    5,    5,    5,    4,    5,    0,    5,    5,    5,
        5,    4,    0,    0,    3,    0,    0,    5,    5,    5,
        5,    5,    2,    5,    5,    5,    5,    0,    5,    5,
        5,    5,    5,    5,    1,    5,    5,    5,    5,    5,
        5,    0,    0,    5,    5,    5,    0,    5,    5,    5,
        0,    0,    0,    0,    0,    0,    0,    0,    5,    5,

        5,    5,    5,    5,    5,    5,    0,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    0,
        0,    5,    5,    1,    0,    5,    5,    0,    0,    0,
        0,    0,    0,    0,    5,    5,    5,    5,    5,    0,
        5,    5,    5,    5,    5,    5,    0,    0,    5,    5,
        0,    5,    5,    0,    0,    0,    0,    0,    0,    5,
        5,    5,    0,    5,    5,    1,    5,    0,    0,    5,
        5,    4,    5,    0,    0,    0,    0,    0,    5,    5,
        5,    5,    5,    5,    0,    0,    5,    0,    0,    0,
        0,    0,    5,    5,    5,    5,    0,    0,    5,    0,

        0,    0,    0,    5,    5,    5,    5,    0,    0,    5,
        0,    0,    0,    5,    5,    5,    1,    1,    0,    0,
        0,    5,    5,    0,    0,    5,    0,    0,    5,    0,
        0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    6,    7,
        8,    9,   10,    1,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,   17,
       18,   19,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   25,   25,   29,   25,   30,   31,   25,
       25,   32,   33,   34,   35,   36,   25,   25,   37,   25,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
       67,   25,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[72] =
    {   0,
        1,    2,    3,    2,    1,    1,    4,    5,    1,    1,
        1,    1,    1,    6,    6,    5,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    1,    1,
        1,    6,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    1,    1,
        1
    } ;

static yyconst short int yy_base[340] =
    {   0,
        0,    0,  464, 1418,   70, 1418,   68, 1418, 1418,   63,
       68,   72,   63,   76,   80,  431,  430, 1418,  429,   94,
       98,  104,  108,  112,  116,  126,  120,  130,  134,  142,
      151,  155,  159,  167,  168,  141,  174,  178,  203,  187,
      210,  238,  434, 1418,   95,  147, 1418,  439,   89,  189,
      215,    0, 1418,  125,  150,  221,  232, 1418,  247,  214,
      251,  255,  261,  265,  269,  273,  279,  286,  292,  296,
      304,  312,  316,  320,  324,  328,  335,  336,  343,  344,
      351,  352,  358,  362,  370,  371,  378,  379,  386,  450,
      392,  420,  400,  409,  399,  436,  413,  424,  437,  468,

      472,  478,  421,  290,    0,  178,  280,  490,  493,  497,
      501,  505,  520,  521,  528,  535,  539,  545,  546,  552,
      556,  564,  565,  572,  573,  579,  580,  586,  593,  587,
      594,  601,  610,  617,  611,  623,  374,  631,  624,  640,
      641,  647,  653,  657,  665,  666,  672,  679,  687,  691,
      695,  699,  360,  706, 1418,  713,  721,  726,  732,  753,
      733,  757,  763,  764,  770,  774,  780,  784,  788,  792,
      799,  800,  806,  807,  813,  817,  823,  824,  832,  838,
      846,  378,  850,  855,  867,  871,  367,  878,  882,  886,
      909,  602,  386,  379,  382,  375,  376,  361,  892,  901,

      913,  932,  941,  942,  948,  949,  342,  955,  956,  962,
      966,  973,  977,  983,  987,  991,  995,  999, 1005,  322,
     1013, 1016, 1024, 1030,  323, 1034, 1041,  868,  336,  336,
      341,  318,  329,  312, 1042, 1050, 1056, 1057, 1064,  294,
     1065, 1072, 1082, 1090, 1091, 1098,  292, 1102, 1107, 1113,
      286, 1120, 1119,  305,  292,  285,  289,  281,  273, 1129,
     1133, 1141,  241, 1148, 1155, 1156, 1165,  237, 1130, 1166,
     1175, 1418, 1176,  252,  255,  258,  248,  240, 1184, 1185,
     1192, 1191, 1198, 1199,  213, 1206, 1205,  237,  240,  234,
      228,  222, 1223, 1224, 1230, 1231,  187, 1237, 1248,  216,

      196,  186,  181, 1256, 1260, 1264, 1268,  153, 1274, 1290,
      141,  154,  144, 1294, 1298, 1304, 1418, 1275,  131,  125,
      103, 1305, 1311,   97,   86, 1315,   84,   92, 1328,   75,
       64,   65, 1418, 1389, 1394, 1400,   83, 1406, 1411
    } ;

static yyconst short int yy_def[340] =
    {   0,
      333,    1,  333,  333,  333,  333,  334,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  333,  333,  333,  334,  333,  334,  333,  333,
      333,  336,  333,  333,  333,  333,  333,  333,  333,  337,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  338,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,

      335,  335,  333,  333,  336,  333,  337,  339,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  333,  333,  337,  335,
      335,  335,  335,  335,  335,  335,  333,  335,  335,  335,
      335,  335,  333,  333,  333,  339,  333,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  333,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  333,  339,  335,  335,  335,  333,  335,  335,  335,
      333,  333,  333,  333,  333,  333,  333,  333,  335,  335,

      335,  335,  335,  335,  335,  335,  333,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  333,
      339,  335,  335,  335,  333,  335,  335,  333,  333,  333,
      333,  333,  333,  333,  335,  335,  335,  335,  335,  333,
      335,  335,  335,  335,  335,  335,  333,  339,  335,  335,
      333,  335,  335,  333,  333,  333,  333,  333,  333,  335,
      335,  335,  333,  335,  335,  335,  335,  333,  339,  335,
      335,  333,  335,  333,  333,  333,  333,  333,  335,  335,
      335,  335,  335,  335,  333,  339,  335,  333,  333,  333,
      333,  333,  335,  335,  335,  335,  333,  339,  335,  333,

      333,  333,  333,  335,  335,  335,  335,  333,  339,  335,
      333,  333,  333,  335,  335,  335,  333,  339,  333,  333,
      333,  335,  335,  333,  333,  335,  333,  333,  335,  333,
      333,  333,    0,  333,  333,  333,  333,  333,  333
    } ;

static yyconst short int yy_nxt[1490] =
    {   0,
        4,    5,    6,    5,    7,    8,    8,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   23,   23,   23,   23,   24,   23,   25,
       23,   26,   27,   23,   23,   28,   23,    8,   18,    8,
       18,    4,   29,   23,   30,   31,   32,   33,   23,   23,
       34,   23,   23,   35,   36,   37,   38,   23,   23,   39,
       23,   40,   41,   23,   23,   42,   23,    8,   43,    8,
       44,   45,   47,   45,   49,   53,   50,   51,   52,   49,
       53,   50,   51,   53,  108,   54,   54,   55,  192,   56,
       56,   55,  332,   57,   57,   59,   45,   59,   45,   59,

       60,   59,   54,   54,   60,   59,   48,   59,  192,   59,
       60,   59,  331,   59,   60,   59,  330,   59,   60,   59,
      328,   59,   60,   59,  327,   62,   60,   59,   63,   59,
       64,   59,   60,   59,  192,   59,   60,   59,   54,   54,
       60,   66,   59,   59,   59,   59,   67,   60,   60,   69,
       68,   47,   59,   71,   59,  325,   59,   60,   59,  324,
       59,   60,   59,  106,  106,   60,   65,  321,   59,   59,
       59,   59,   70,   60,   60,   59,  320,   59,   73,   59,
       60,   59,  319,   93,   60,   48,   72,   74,   59,   75,
       59,  106,  106,   60,   76,   78,   77,   81,   79,  317,

       55,   80,   56,   56,   59,   86,   59,   82,   83,   60,
       84,   59,  192,   59,   82,  107,   60,  107,   87,  313,
       85,   88,   89,   90,   92,  312,   55,   91,  104,  104,
       94,   95,   55,   96,   56,   56,  100,   97,  311,   59,
       98,   59,  308,   55,   60,   57,   57,  192,   59,   99,
       59,  303,   59,   60,   59,  302,   59,   60,   59,  301,
      300,   60,   59,  297,   59,  101,   59,   60,   59,  292,
       59,   60,   59,  291,   59,   60,   59,  290,  289,   60,
       59,  107,   59,  107,  111,   60,  109,   59,  288,   59,
      285,  110,   60,   59,  102,   59,  272,   59,   60,   59,

      278,   55,   60,  104,  104,   59,  113,   59,  114,  192,
       60,  116,  277,   59,  115,   59,  276,   59,   60,   59,
      275,   59,   60,   59,  274,   59,   60,   59,  112,   59,
       60,   59,  272,  268,   60,  118,   59,   59,   59,   59,
      263,   60,   60,  259,   59,   59,   59,   59,  258,   60,
       60,  257,   59,   59,   59,   59,  117,   60,   60,   59,
      256,   59,  119,   59,   60,   59,  255,  254,   60,  122,
      121,   59,   59,   59,   59,  120,   60,   60,  125,   59,
       59,   59,   59,  251,   60,   60,  247,   59,  123,   59,
      127,  240,   60,   59,  234,   59,  124,  126,   60,  233,

       59,   59,   59,   59,  232,   60,   60,   82,  231,  230,
       59,  128,   59,  132,   59,   60,  147,  229,  129,   60,
      225,   59,  130,   59,  220,   59,   60,   59,   53,  182,
       60,  131,  153,  141,  133,  135,  134,   59,   59,   59,
       59,  333,   60,   60,   82,  103,   58,   58,   53,  136,
      137,  138,  144,  138,  137,  137,  139,  137,  137,  137,
      137,  137,  137,  333,  142,  137,  137,  137,  137,   59,
      145,   59,  333,   59,   60,   59,  143,  333,   60,   59,
      146,   59,  148,  333,   60,   82,  333,  137,  137,  137,
      137,  154,  333,  154,   59,  149,   59,  155,   59,   60,

       59,  333,   59,   60,   59,  157,   59,   60,   59,  333,
      333,   60,  158,  333,  150,  333,  333,  137,  137,  137,
      137,   59,   59,   59,   59,  159,   60,   60,  333,   59,
      333,   59,  160,  151,   60,  333,   59,  152,   59,  333,
       59,   60,   59,  162,   82,   60,   59,   59,   59,   59,
      333,   60,   60,   59,  333,   59,   82,   59,   60,   59,
      333,  333,   60,  163,  161,   59,   59,  168,   59,  333,
       60,   60,  165,   59,   59,   59,   59,  333,   60,   60,
       59,   59,   59,   59,  333,   60,   60,   59,   59,   59,
       59,   82,   60,   60,   59,   59,   59,   59,  167,   60,

       60,  164,   59,  228,   59,  228,  333,   60,  166,  155,
      333,   59,   59,   59,   59,  169,   60,   60,   59,  333,
       59,  170,  173,   60,   59,  107,   59,  107,  333,   60,
      174,  333,   59,  171,   59,  333,  172,   60,  333,  175,
      177,   59,   59,   59,   59,  333,   60,   60,   59,  176,
       59,  333,  333,   60,   59,  333,   59,  180,   59,   60,
       59,  333,  178,   60,   82,  181,   59,   59,   59,   59,
      179,   60,   60,   59,  333,   59,  333,  333,   60,  183,
       59,  333,   59,  333,  333,   60,  182,  185,   59,  186,
       59,  333,   59,   60,   59,  184,   59,   60,   59,  333,

       59,   60,   59,   82,  333,   60,  333,  154,  333,  154,
       82,   82,   82,  155,  154,  333,  154,  333,  187,  333,
      155,  157,  191,  192,  191,  188,  333,   59,  157,   59,
      333,  333,   60,   59,   59,   59,   59,  333,   60,   60,
      193,  194,  195,  333,  333,  190,   82,  333,  196,  189,
      333,  333,  197,  198,   59,  200,   59,  333,   59,   60,
       59,  333,  199,   60,   59,   59,   59,   59,  333,   60,
       60,   59,  201,   59,  333,   59,   60,   59,  333,  202,
       60,   59,  203,   59,  333,   59,   60,   59,  333,   59,
       60,   59,  333,   59,   60,   59,  333,  333,   60,  205,

       59,   59,   59,   59,  333,   60,   60,   59,   59,   59,
       59,  333,   60,   60,   59,  333,   59,  204,   59,   60,
       59,  333,  333,   60,   59,   59,   59,   59,  333,   60,
       60,  333,  333,   59,  206,   59,  208,  333,   60,   59,
       82,   59,  210,  333,   60,  207,  333,   59,  209,   59,
      333,  154,   60,  154,  333,  333,   59,  155,   59,   82,
      333,   60,  333,  213,  333,  157,  212,  211,   59,  228,
       59,  228,   59,   60,   59,  155,  214,   60,  215,   59,
      333,   59,  217,   59,   60,   59,  216,   59,   60,   59,
      333,  333,   60,   59,  333,   59,  221,  218,   60,  333,

      333,  222,   59,  333,   59,  219,  333,   60,  333,  333,
      191,  192,  191,  333,   59,  235,   59,  333,  333,   60,
      236,  223,  333,  333,  224,  226,  333,  333,  193,  194,
      195,  333,  227,   59,  237,   59,  196,  333,   60,   82,
      197,  198,   59,   59,   59,   59,  333,   60,   60,   59,
       59,   59,   59,  333,   60,   60,   59,   59,   59,   59,
      333,   60,   60,   59,  239,   59,  333,   59,   60,   59,
      333,  333,   60,  163,   59,  333,   59,  333,   59,   60,
       59,  333,  333,   60,   59,  333,   59,  238,   59,   60,
       59,  333,   59,   60,   59,  333,   59,   60,   59,  333,

       59,   60,   59,   82,  333,   60,   59,  333,   59,   82,
       82,   60,  224,  333,  154,   82,  154,   59,  333,   59,
      155,  241,   60,  242,   82,   59,  333,   59,  157,   82,
       60,   59,   82,   59,  333,   59,   60,   59,  333,  333,
       60,  244,   59,   59,   59,   59,  333,   60,   60,  245,
      243,   59,  333,   59,  333,  246,   60,   59,   59,   59,
       59,  333,   60,   60,  260,   59,   59,   59,   59,  333,
       60,   60,  333,   59,  333,   59,  333,  248,   60,  261,
      249,  250,  333,   59,  252,   59,  333,  333,   60,  262,
      333,   59,   59,   59,   59,  163,   60,   60,  333,   59,

      253,   59,  333,  154,   60,  154,  333,  333,   59,  155,
       59,  264,  333,   60,   59,  333,   59,  157,   82,   60,
       59,   59,   59,   59,  333,   60,   60,  333,   82,  265,
       59,  154,   59,  154,   59,   60,   59,  155,  333,   60,
      267,  333,   59,  269,   59,  157,  333,   60,  270,   59,
      266,   59,   82,  333,   60,  280,   59,   59,   59,   59,
      333,   60,   60,  333,  281,   82,   59,   59,   59,   59,
      279,   60,   60,  333,  271,  273,   59,   59,   59,   59,
      333,   60,   60,  286,  333,   59,   59,   59,   59,  282,
       60,   60,   59,   59,   59,   59,  333,   60,   60,   59,

       59,   59,   59,  333,   60,   60,   59,  154,   59,  154,
      333,   60,  293,  155,  333,  294,  283,  333,  333,  287,
      284,  157,   82,  163,   59,   59,   59,   59,  333,   60,
       60,   59,   59,   59,   59,  333,   60,   60,  154,  333,
      154,   82,  333,  333,  155,  333,  333,  295,  296,   59,
      304,   59,  157,  333,   60,  299,  298,   59,  305,   59,
       82,   59,   60,   59,  333,   59,   60,   59,  333,   59,
       60,   59,  333,  306,   60,  154,  154,  154,  154,  333,
      315,  155,  155,  333,  333,  333,  333,  307,  314,  157,
      157,   59,  309,   59,  333,   59,   60,   59,  333,   59,

       60,   59,  333,  310,   60,   59,   59,   59,   59,  333,
       60,   60,   59,  333,   59,  316,   59,   60,   59,  333,
      318,   60,  333,   82,  333,  333,  322,  163,  163,   59,
      333,   59,  333,  333,   60,  333,   82,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      323,  333,  333,  333,  333,  326,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  329,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,   82,   46,
       46,   46,   46,   46,   46,   61,  333,   61,  333,   61,

      105,  105,  333,  105,  105,  105,  140,  140,  333,  140,
      140,  140,  156,  333,  333,  156,  156,    3,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333
    } ;

static yyconst short int yy_chk[1490] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    7,    5,   10,   13,   10,   10,   11,   11,
       13,   11,   11,   12,  337,   12,   12,   14,  332,   14,
       14,   15,  331,   15,   15,   20,   45,   20,   45,   21,

       20,   21,   49,   49,   21,   22,    7,   22,  330,   23,
       22,   23,  328,   24,   23,   24,  327,   25,   24,   25,
      325,   27,   25,   27,  324,   20,   27,   26,   21,   26,
       22,   28,   26,   28,  321,   29,   28,   29,   54,   54,
       29,   24,   36,   30,   36,   30,   25,   36,   30,   26,
       25,   46,   31,   27,   31,  320,   32,   31,   32,  319,
       33,   32,   33,   55,   55,   33,   22,  313,   34,   35,
       34,   35,   26,   34,   35,   37,  312,   37,   29,   38,
       37,   38,  311,   36,   38,   46,   28,   29,   40,   29,
       40,  106,  106,   40,   29,   30,   29,   31,   30,  308,

       50,   30,   50,   50,   39,   33,   39,   31,   32,   39,
       32,   41,  303,   41,   34,   60,   41,   60,   33,  302,
       32,   34,   34,   34,   35,  301,   51,   34,   51,   51,
       37,   38,   56,   38,   56,   56,   40,   38,  300,   42,
       38,   42,  297,   57,   42,   57,   57,  292,   59,   39,
       59,  291,   61,   59,   61,  290,   62,   61,   62,  289,
      288,   62,   63,  285,   63,   41,   64,   63,   64,  278,
       65,   64,   65,  277,   66,   65,   66,  276,  275,   66,
       67,  107,   67,  107,   64,   67,   62,   68,  274,   68,
      268,   63,   68,   69,   42,   69,  263,   70,   69,   70,

      259,  104,   70,  104,  104,   71,   66,   71,   67,  258,
       71,   69,  257,   72,   68,   72,  256,   73,   72,   73,
      255,   74,   73,   74,  254,   75,   74,   75,   65,   76,
       75,   76,  251,  247,   76,   71,   77,   78,   77,   78,
      240,   77,   78,  234,   79,   80,   79,   80,  233,   79,
       80,  232,   81,   82,   81,   82,   70,   81,   82,   83,
      231,   83,   72,   84,   83,   84,  230,  229,   84,   75,
       74,   85,   86,   85,   86,   73,   85,   86,   78,   87,
       88,   87,   88,  225,   87,   88,  220,   89,   76,   89,
       80,  207,   89,   91,  198,   91,   77,   79,   91,  197,

       95,   93,   95,   93,  196,   95,   93,   84,  195,  194,
       94,   81,   94,   86,   97,   94,   97,  193,   83,   97,
      187,   92,   84,   92,  182,   98,   92,   98,  153,  137,
       98,   85,  103,   91,   87,   89,   88,   96,   99,   96,
       99,   48,   96,   99,   95,   43,   19,   17,   16,   89,
       90,   90,   93,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,    3,   92,   90,   90,   90,   90,  100,
       94,  100,    0,  101,  100,  101,   92,    0,  101,  102,
       96,  102,   99,    0,  102,   98,    0,   90,   90,   90,
       90,  108,    0,  108,  109,   99,  109,  108,  110,  109,

      110,    0,  111,  110,  111,  108,  112,  111,  112,    0,
        0,  112,  109,    0,  100,    0,    0,   90,   90,   90,
       90,  113,  114,  113,  114,  110,  113,  114,    0,  115,
        0,  115,  111,  101,  115,    0,  116,  102,  116,    0,
      117,  116,  117,  113,  114,  117,  118,  119,  118,  119,
        0,  118,  119,  120,    0,  120,  115,  121,  120,  121,
        0,    0,  121,  116,  112,  122,  123,  122,  123,    0,
      122,  123,  118,  124,  125,  124,  125,    0,  124,  125,
      126,  127,  126,  127,    0,  126,  127,  128,  130,  128,
      130,  119,  128,  130,  129,  131,  129,  131,  121,  129,

      131,  117,  132,  192,  132,  192,    0,  132,  120,  192,
        0,  133,  135,  133,  135,  123,  133,  135,  134,    0,
      134,  124,  127,  134,  136,  139,  136,  139,    0,  136,
      128,    0,  138,  125,  138,    0,  126,  138,    0,  129,
      131,  140,  141,  140,  141,    0,  140,  141,  142,  130,
      142,    0,    0,  142,  143,    0,  143,  135,  144,  143,
      144,    0,  132,  144,  133,  136,  145,  146,  145,  146,
      134,  145,  146,  147,    0,  147,    0,    0,  147,  139,
      148,    0,  148,    0,    0,  148,  138,  141,  149,  142,
      149,    0,  150,  149,  150,  140,  151,  150,  151,    0,

      152,  151,  152,  144,    0,  152,    0,  154,    0,  154,
      143,  145,  146,  154,  156,    0,  156,    0,  147,    0,
      156,  154,  157,  157,  157,  148,    0,  158,  156,  158,
        0,    0,  158,  159,  161,  159,  161,    0,  159,  161,
      157,  157,  157,    0,    0,  151,  150,    0,  157,  149,
        0,    0,  157,  157,  160,  159,  160,    0,  162,  160,
      162,    0,  158,  162,  163,  164,  163,  164,    0,  163,
      164,  165,  160,  165,    0,  166,  165,  166,    0,  161,
      166,  167,  162,  167,    0,  168,  167,  168,    0,  169,
      168,  169,    0,  170,  169,  170,    0,    0,  170,  165,

      171,  172,  171,  172,    0,  171,  172,  173,  174,  173,
      174,    0,  173,  174,  175,    0,  175,  164,  176,  175,
      176,    0,    0,  176,  177,  178,  177,  178,    0,  177,
      178,    0,    0,  179,  166,  179,  169,    0,  179,  180,
      167,  180,  172,    0,  180,  168,    0,  181,  170,  181,
        0,  183,  181,  183,    0,    0,  184,  183,  184,  171,
        0,  184,    0,  175,    0,  183,  174,  173,  185,  228,
      185,  228,  186,  185,  186,  228,  176,  186,  177,  188,
        0,  188,  179,  189,  188,  189,  178,  190,  189,  190,
        0,    0,  190,  199,    0,  199,  183,  180,  199,    0,

        0,  184,  200,    0,  200,  181,    0,  200,    0,    0,
      191,  191,  191,    0,  201,  199,  201,    0,    0,  201,
      200,  185,    0,    0,  186,  188,    0,    0,  191,  191,
      191,    0,  189,  202,  201,  202,  191,    0,  202,  190,
      191,  191,  203,  204,  203,  204,    0,  203,  204,  205,
      206,  205,  206,    0,  205,  206,  208,  209,  208,  209,
        0,  208,  209,  210,  203,  210,    0,  211,  210,  211,
        0,    0,  211,  205,  212,    0,  212,    0,  213,  212,
      213,    0,    0,  213,  214,    0,  214,  202,  215,  214,
      215,    0,  216,  215,  216,    0,  217,  216,  217,    0,

      218,  217,  218,  204,    0,  218,  219,    0,  219,  206,
      208,  219,  211,    0,  221,  209,  221,  222,    0,  222,
      221,  210,  222,  212,  213,  223,    0,  223,  221,  214,
      223,  224,  215,  224,    0,  226,  224,  226,    0,    0,
      226,  217,  227,  235,  227,  235,    0,  227,  235,  218,
      216,  236,    0,  236,    0,  219,  236,  237,  238,  237,
      238,    0,  237,  238,  235,  239,  241,  239,  241,    0,
      239,  241,    0,  242,    0,  242,    0,  221,  242,  236,
      222,  223,    0,  243,  226,  243,    0,    0,  243,  237,
        0,  244,  245,  244,  245,  239,  244,  245,    0,  246,

      227,  246,    0,  248,  246,  248,    0,    0,  249,  248,
      249,  241,    0,  249,  250,    0,  250,  248,  238,  250,
      253,  252,  253,  252,    0,  253,  252,    0,  243,  242,
      260,  269,  260,  269,  261,  260,  261,  269,    0,  261,
      246,    0,  262,  248,  262,  269,    0,  262,  249,  264,
      244,  264,  245,    0,  264,  261,  265,  266,  265,  266,
        0,  265,  266,    0,  262,  253,  267,  270,  267,  270,
      260,  267,  270,    0,  250,  252,  271,  273,  271,  273,
        0,  271,  273,  269,    0,  279,  280,  279,  280,  264,
      279,  280,  282,  281,  282,  281,    0,  282,  281,  283,

      284,  283,  284,    0,  283,  284,  287,  286,  287,  286,
        0,  287,  279,  286,    0,  280,  265,    0,    0,  270,
      267,  286,  273,  281,  293,  294,  293,  294,    0,  293,
      294,  295,  296,  295,  296,    0,  295,  296,  298,    0,
      298,  271,    0,    0,  298,    0,    0,  282,  283,  299,
      293,  299,  298,    0,  299,  287,  286,  304,  294,  304,
      284,  305,  304,  305,    0,  306,  305,  306,    0,  307,
      306,  307,    0,  295,  307,  309,  318,  309,  318,    0,
      305,  309,  318,    0,    0,    0,    0,  296,  304,  309,
      318,  310,  298,  310,    0,  314,  310,  314,    0,  315,

      314,  315,    0,  299,  315,  316,  322,  316,  322,    0,
      316,  322,  323,    0,  323,  306,  326,  323,  326,    0,
      309,  326,    0,  307,    0,    0,  315,  314,  322,  329,
        0,  329,    0,    0,  329,    0,  310,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      316,    0,    0,    0,    0,  323,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  326,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  329,  334,
      334,  334,  334,  334,  334,  335,    0,  335,    0,  335,

      336,  336,    0,  336,  336,  336,  338,  338,    0,  338,
      338,  338,  339,    0,    0,  339,  339,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
#line 3 "lex.l"
	#include <string.h>
	#include <stdlib.h>
	#include "uthash.h" 

	typedef struct {
		int line_no;
		int col_no;
		char type[100];
	} Content;

	typedef struct token{
		char val[100];      /* Key */
		Content* content;
		UT_hash_handle hh;
	} Lexeme;

	void addHashUtil(char* yytext, char* type, int line, int col);
	void addHash(char* type, int line_no, char* value, int col_no);
	Lexeme* findHash(char* str);
	void printHash();
	void printLines();

	Lexeme* lexemes = NULL;  /* hash array */
	int line=1, col=1;
#line 830 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 52 "lex.l"

#line 983 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 334 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1418 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 53 "lex.l"
{
							// printf("%s\n", yytext);
							addHashUtil(yytext, "Keyword", line, col);
							col += yyleng;
						}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "lex.l"
{
							// printf("%s\n", yytext);
							addHashUtil(yytext, "Predefined Type", line, col);
							col += yyleng;
						}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "lex.l"
{
							// printf("%s\n", yytext);
							strtok(yytext, "(");
							addHashUtil(yytext, "Function", line, col);
							col += yyleng;
						}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 69 "lex.l"
{
							// printf("%s\n", yytext);
							addHashUtil(yytext, "Special Operator", line, col);
							col += yyleng;
						}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 74 "lex.l"
{
							// printf("%s\n", yytext);
							addHashUtil(yytext, "Identifier", line, col);
							col += yyleng;
						}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 79 "lex.l"
{
							// printf("%s\n", yytext);
							addHashUtil(yytext, "Integer", line, col);
							col += yyleng;
						}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 84 "lex.l"
{
							// printf("%s\n", yytext);
							addHashUtil(yytext, "Real No.", line, col);
							col += yyleng;
						}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 89 "lex.l"
{
							// printf("%s\n", yytext);
							addHashUtil(yytext, "String", line, col);
							col += yyleng;
						}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 94 "lex.l"
{
							col += yyleng;
						}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 97 "lex.l"
{
							line++;
							col=1;
						}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 101 "lex.l"
{
							col += yyleng;
						}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 104 "lex.l"
{
							// printf("%s\n", yytext);
							addHashUtil(yytext, "Operator", line, col);
							col += yyleng;
						}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 109 "lex.l"
{
							// printf("%s\n", yytext);
							addHashUtil(yytext, "Comment", line, col);
							col += yyleng;
						}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 114 "lex.l"
{
							col += yyleng;
						}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 117 "lex.l"
{
							printf("");
						}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 120 "lex.l"
ECHO;
	YY_BREAK
#line 1198 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 334 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 334 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 333);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 120 "lex.l"


void addHashUtil(char* yytext, char* type, int line, int col) {
    Lexeme* temp = (Lexeme*)malloc(sizeof(Lexeme));
    temp = findHash(yytext);
    if(temp == NULL)
        addHash(type, line, yytext, col);
}

void addHash(char* type, int line_no, char* value, int col_no) {
    Lexeme* temp = (Lexeme*)malloc(sizeof(Lexeme));
	// temp->val = value;
	strcpy(temp->val, value);
    temp->content = (Content*)malloc(sizeof(Content));
    temp->content->line_no = line_no;
    temp->content->col_no = col_no;
    // temp->content->type = type;
	strcpy(temp->content->type, type);
    HASH_ADD_KEYPTR(hh, lexemes, temp->val, strlen(temp->val), temp);
	// printf("%s with value \'%s\' found in line %d at column %d\n", temp->content->type, temp->val, temp->content->line_no, temp->content->col_no);
	printf("%10s|%10d\t|\t%5d\t|\t%-50s\t|\t%-20s|\n"," ", line, col, yytext, type);
	printLines();
    free(temp);
}

Lexeme* findHash(char* str) {
    Lexeme* temp = (Lexeme*)malloc(sizeof(Lexeme));
    HASH_FIND_STR(lexemes, str, temp);
    return temp;
}

void printLines() {
	for(int i=0;i<133;i++) {
		if(i<10) {
			printf(" ");
			continue;
		}
		printf("-");
	}
	printf("\n");
}

void printLinesUnderScore() {
	for(int i=0;i<133;i++) {
		if(i<10) {
			printf(" ");
			continue;
		}
		printf("_");
	}
	printf("\n");
}

int main() {
	printLinesUnderScore();
	printLines();
	printf("%10s|%10s\t|\t%5s\t|\t%-50s\t|\t%-20s|\n", " ", "LineNo", "ColNo", "Token", "Type");
	printLinesUnderScore();
	printLines();
	yylex();
	return 0;
}