
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 20
#define YY_END_OF_BUFFER 21
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[336] =
    {   0,
        0,    0,   21,   20,   13,   14,   15,   15,   16,   16,
       16,   18,   16,   10,   10,   19,   16,   16,   16,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,   15,   16,   13,    0,   12,    0,    0,
       10,   10,   17,   16,   11,    0,   11,   10,   16,    0,
        0,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    5,    9,    9,
        9,    9,    9,    5,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    8,    9,

        9,    9,    9,    9,    0,   10,   17,   11,    0,    0,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    8,    9,    9,    9,    9,    9,
        9,    9,    3,    9,    9,    9,    9,    9,    9,    9,
        0,    0,    0,    9,    9,    9,    9,    9,    8,    9,
        0,    9,    9,    9,    9,    8,    0,    0,    7,    0,
        0,    9,    9,    9,    9,    9,    9,    6,    9,    9,
        9,    9,    0,    9,    9,    9,    9,    9,    9,    5,
        9,    9,    9,    9,    9,    9,    0,    0,    9,    9,
        9,    0,    9,    9,    9,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    0,    9,    9,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    0,    0,    9,
        9,    5,    0,    9,    9,    0,    0,    0,    0,    0,
        0,    0,    0,    9,    9,    9,    9,    9,    0,    9,
        2,    9,    9,    9,    9,    9,    0,    0,    9,    9,
        0,    9,    9,    0,    0,    0,    0,    0,    0,    0,
        9,    9,    0,    9,    9,    4,    5,    9,    0,    0,
        9,    9,    8,    9,    0,    0,    0,    0,    0,    0,
        9,    9,    9,    9,    9,    0,    0,    9,    0,    0,

        0,    0,    0,    0,    9,    9,    9,    0,    0,    9,
        0,    0,    0,    0,    9,    9,    9,    0,    0,    9,
        0,    0,    9,    9,    5,    5,    0,    0,    9,    0,
        9,    0,    9,    0,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    6,    7,
        8,    9,   10,    1,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,   17,
       18,   19,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   25,   25,   29,   25,   30,   31,   25,
       25,   32,   33,   34,   35,   36,   25,   25,   37,   25,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
       67,   25,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[72] =
    {   0,
        1,    2,    3,    2,    1,    1,    4,    5,    1,    1,
        1,    1,    1,    6,    6,    5,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    1,    1,
        1,    6,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[342] =
    {   0,
        0,    0,  507, 1426,   70, 1426,   68, 1426, 1426,   63,
       68,   72,   63,   76,   80,  484,  483, 1426,  481,   94,
       98,  104,  108,  112,  116,  120,  126,  130,  134,  138,
      150,  156,  164,  168,  177,  178,  186,  193,  204,  210,
      219,  220,  235,  484, 1426,   95,  104, 1426,  490,   89,
      147,  162,    0, 1426,  133,  172,  229,  233, 1426,  247,
      194,  259,  266,  270,  276,  277,  283,  287,  293,  300,
      304,  308,  312,  323,  324,  331,  332,  338,  339,  345,
      349,  353,  357,  361,  368,  369,  379,  383,  387,  391,
      401,  465,  405,  435,  409,  417,  418,  441,  429,  448,

      452,  483,  456,  487,  476,  241,    0,  352,  284,  301,
      493,  510,  517,  518,  524,  536,  544,  525,  548,  554,
      555,  562,  563,  569,  577,  578,  584,  585,  591,  592,
      598,  607,  599,  611,  617,  621,  629,  635,  643,  649,
      412,  653,  346,  659,  663,  669,  673,  689,  693,  697,
      701,  709,  715,  716,  722,  723,  392,  430, 1426,  636,
      730,  739,  735,  762,  753,  763,  773,  777,  781,  787,
      791,  799,  800,  806,  807,  814,  818,  822,  826,  830,
      834,  840,  841,  847,  861,  865,  410,  869,  872,  876,
      885,  399,  886,  893,  899,  926,  677,  408,  404,  401,

      396,  393,  393,  380,  903,  913,  933,  907,  958,  962,
      934,  966,  970,  360,  974,  981,  987,  991,  995,  999,
     1005, 1009, 1013, 1017, 1021, 1025, 1031,  341, 1006, 1032,
     1041, 1042,  336, 1050, 1056,  948,  364,  361,  360,  344,
      343,  342,  326, 1060, 1068, 1077, 1083, 1087,  307, 1100,
     1101, 1108, 1116, 1120, 1124, 1128,  290, 1132, 1135, 1139,
      275, 1147, 1148,  300,  284,  267,  272,  258,  246,  243,
     1154, 1155,  209, 1163, 1171, 1178, 1185, 1186,  208, 1084,
     1195, 1202, 1426, 1206,  222,  228,  226,  211,  210,  201,
     1210, 1214, 1218, 1222, 1228,  168, 1232, 1243,  192,  189,

      183,  178,  165,  152, 1250, 1254, 1258,  113, 1264, 1272,
      142,  126,  119,  117, 1280, 1284, 1293,   97, 1300, 1299,
       93,  101, 1303, 1307, 1426, 1315,   92,   85, 1320,   85,
     1328,   60, 1336,   55, 1426, 1397, 1402, 1408,   83, 1414,
     1419
    } ;

static const flex_int16_t yy_def[342] =
    {   0,
      335,    1,  335,  335,  335,  335,  336,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  335,  335,  335,  336,  335,  336,  335,
      335,  335,  338,  335,  335,  335,  335,  335,  335,  335,
      339,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  340,  337,  337,  337,  337,  337,  337,  337,  337,

      337,  337,  337,  337,  335,  335,  338,  335,  339,  341,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      335,  335,  339,  337,  337,  337,  337,  337,  337,  337,
      335,  337,  337,  337,  337,  337,  335,  335,  335,  341,
      335,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  335,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  335,  341,  337,  337,
      337,  335,  337,  337,  337,  335,  335,  335,  335,  335,

      335,  335,  335,  335,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  335,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  335,  341,  337,
      337,  337,  335,  337,  337,  335,  335,  335,  335,  335,
      335,  335,  335,  337,  337,  337,  337,  337,  335,  337,
      337,  337,  337,  337,  337,  337,  335,  341,  337,  337,
      335,  337,  337,  335,  335,  335,  335,  335,  335,  335,
      337,  337,  335,  337,  337,  337,  337,  337,  335,  341,
      337,  337,  335,  337,  335,  335,  335,  335,  335,  335,
      337,  337,  337,  337,  337,  335,  341,  337,  335,  335,

      335,  335,  335,  335,  337,  337,  337,  335,  341,  337,
      335,  335,  335,  335,  337,  337,  337,  335,  341,  337,
      335,  335,  337,  337,  335,  341,  335,  335,  337,  335,
      337,  335,  337,  335,    0,  335,  335,  335,  335,  335,
      335
    } ;

static const flex_int16_t yy_nxt[1498] =
    {   0,
        4,    5,    6,    5,    7,    8,    8,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   24,   24,   24,   25,   24,   26,
       24,   27,   28,   24,   24,   29,   24,    8,   18,    8,
       18,    4,   30,   24,   31,   32,   33,   34,   24,   24,
       35,   24,   24,   36,   37,   38,   39,   24,   24,   40,
       24,   41,   42,   24,   24,   43,   24,    8,   44,    8,
       45,   46,   48,   46,   50,   54,   51,   52,   53,   50,
       54,   51,   52,   54,  110,   55,   55,   56,  197,   57,
       57,   56,  334,   58,   58,   60,   46,   60,   46,   60,

       61,   60,   55,   55,   61,   60,   49,   60,   48,   60,
       61,   60,  332,   60,   61,   60,  197,   60,   61,   60,
      330,   60,   61,   60,  328,   63,   61,   60,   64,   60,
       65,   60,   61,   60,  327,   60,   61,   60,   67,   60,
       61,   60,   49,  325,   61,   68,   55,   55,  197,   71,
       69,   60,  322,   60,   70,  197,   61,   60,   56,   60,
       57,   57,   61,   73,  321,   60,   66,   60,  318,   60,
       61,   60,   72,   56,   61,  106,  106,  197,   60,   60,
       60,   60,   75,   61,   61,  108,  108,   60,  314,   60,
       74,   76,   61,   77,   60,  109,   60,  109,   78,   61,

       79,  197,   83,   80,  313,   60,   81,   60,  312,   82,
       61,   60,   84,   60,   88,  311,   61,   85,  308,   86,
       60,   60,   60,   60,   84,   61,   61,   89,   95,   87,
      304,   90,   91,   92,   94,  303,   60,   93,   60,  302,
       56,   61,   57,   57,   56,  301,   58,   58,   60,   96,
       60,  300,   56,   61,  106,  106,  101,   97,  299,   98,
       60,  296,   60,   99,  283,   61,  100,   60,  102,   60,
      290,   60,   61,   60,  197,  103,   61,   60,   60,   60,
       60,  289,   61,   61,   60,  109,   60,  109,   60,   61,
       60,  104,  288,   61,   60,  113,   60,  111,  287,   61,

      112,   60,  158,   60,  158,   60,   61,   60,  159,   60,
       61,   60,  286,   60,   61,   60,  161,  115,   61,  285,
      116,  283,  117,  119,   60,   60,   60,   60,  118,   61,
       61,  279,   60,   60,   60,   60,  114,   61,   61,   60,
       60,   60,   60,  121,   61,   61,   60,  109,   60,  109,
       60,   61,   60,  273,   60,   61,   60,  270,   60,   61,
       60,  269,   60,   61,   60,  108,  108,   61,  120,   60,
       60,   60,   60,  122,   61,   61,  268,  125,  267,  266,
       60,  124,   60,  123,   60,   61,   60,  128,   60,   61,
       60,  265,   60,   61,   60,  264,  261,   61,  126,  130,

      127,  188,   60,  129,   60,  257,   60,   61,   60,  249,
       60,   61,   60,  243,  133,   61,  242,  131,   60,   60,
       60,   60,  241,   61,   61,  136,  240,  239,  132,  134,
       60,  158,  151,  158,  238,   61,   60,  159,   60,  237,
      135,   61,   60,  137,   60,  161,  145,   61,  138,   60,
      139,   60,  233,   60,   61,   60,  228,   60,   61,   60,
       54,  148,   61,   84,  140,  141,  142,  187,  142,  141,
      141,  143,  141,  141,  141,  141,  141,  141,  149,  146,
      141,  141,  141,  141,   60,  150,   60,  157,   60,   61,
       60,  147,  335,   61,   60,  105,   60,  152,   59,   61,

       59,   54,  141,  141,  141,  141,  335,  335,  335,   84,
      153,   60,  162,   60,  335,  335,   61,  155,   60,   60,
       60,   60,  335,   61,   61,   60,   60,   60,   60,  154,
       61,   61,  141,  141,  141,  141,  335,   60,  163,   60,
      335,  335,   61,  335,  166,   60,  156,   60,  164,   60,
       61,   60,  335,   84,   61,   60,   60,   60,   60,  167,
       61,   61,  335,   60,   60,   60,   60,   84,   61,   61,
       60,  335,   60,  335,  335,   61,  168,  165,   60,   60,
      173,   60,  170,   61,   61,   60,   60,   60,   60,  335,
       61,   61,   60,   60,   60,   60,  335,   61,   61,   60,

       60,   60,   60,  335,   61,   61,  335,   84,   60,  335,
       60,  172,   60,   61,   60,  335,  169,   61,   60,  171,
       60,  335,   60,   61,   60,  335,  335,   61,  174,  335,
       60,  335,   60,  175,  178,   61,   60,  158,   60,  158,
      335,   61,  179,  159,   60,  176,   60,  335,  177,   61,
       60,  161,   60,  180,   60,   61,   60,  335,  335,   61,
       60,  335,   60,  182,   60,   61,   60,  335,  335,   61,
       60,  335,   60,  181,   60,   61,   60,  335,  236,   61,
      236,  335,  183,   84,  159,  335,  335,  335,  184,  185,
       60,  186,   60,  335,   60,   61,   60,  335,   60,   61,

       60,  335,   60,   61,   60,  335,  335,   61,  187,  190,
       60,  191,   60,  335,  189,   61,   60,   60,   60,   60,
      335,   61,   61,   60,   60,   60,   60,  335,   61,   61,
       84,  196,  197,  196,  335,   84,   60,  335,   60,   84,
       60,   61,   60,   84,  335,   61,  335,  192,  335,  198,
      199,  200,  201,  335,   60,  193,   60,  202,  206,   61,
      335,  203,  204,   60,   60,   60,   60,  335,   61,   61,
      335,   84,  195,  335,   60,  205,   60,  194,   60,   61,
       60,  207,   60,   61,   60,  335,  335,   61,   60,  335,
       60,  209,   60,   61,   60,  335,  335,   61,  210,  208,

       60,   60,   60,   60,  335,   61,   61,   60,   60,   60,
       60,  335,   61,   61,  335,   60,  212,   60,  335,   60,
       61,   60,  335,   60,   61,   60,  335,   60,   61,   60,
      335,   60,   61,   60,  211,   60,   61,   60,  335,  335,
       61,   60,   60,   60,   60,  335,   61,   61,   60,  335,
       60,  213,  335,   61,  215,  335,  335,  335,  335,   84,
      218,  214,   60,  216,   60,  335,   60,   61,   60,  335,
      158,   61,  158,   60,  217,   60,  159,   60,   61,   60,
      221,  335,   61,  219,  161,  220,   60,   60,   60,   60,
      335,   61,   61,  222,   60,  223,   60,  225,  335,   61,

       60,  335,   60,  224,   60,   61,   60,  335,   60,   61,
       60,  335,  335,   61,   60,  229,   60,  335,  230,   61,
      226,  335,  335,  335,  227,  335,  244,  196,  197,  196,
      231,  335,  245,  234,   60,   60,   60,   60,  232,   61,
       61,  335,  335,  235,  335,  198,  199,  200,  201,  236,
      335,  236,   84,  202,  246,  159,  335,  203,  204,   60,
      335,   60,  247,   60,   61,   60,  335,   60,   61,   60,
      335,   60,   61,   60,  335,   60,   61,   60,  335,  335,
       61,  168,   60,  335,   60,  248,  335,   61,   60,  335,
       60,  168,   60,   61,   60,   84,   60,   61,   60,  335,

       60,   61,   60,  335,  335,   61,   60,  158,   60,  158,
       60,   61,   60,  159,   60,   61,   60,  335,   60,   61,
       60,  161,   60,   61,   60,  335,   60,   61,   60,   84,
       84,   61,   60,   60,   60,   60,  335,   61,   61,  335,
       84,  251,   60,   60,   60,   60,  335,   61,   61,  252,
      250,   60,   84,   60,  335,   84,   61,   60,   84,   60,
      335,   60,   61,   60,  335,  335,   61,  254,  335,   60,
      258,   60,  335,  335,   61,  255,  253,  335,   60,  335,
       60,  256,  271,   61,   60,  158,   60,  158,   60,   61,
       60,  159,  335,   61,  335,  335,  259,  168,  260,  161,

      262,   60,   60,   60,   60,  335,   61,   61,  335,   60,
      272,   60,  335,  335,   61,  263,  335,   60,  168,   60,
      335,   60,   61,   60,  335,   60,   61,   60,  335,   60,
       61,   60,  335,  158,   61,  158,   60,  297,   60,  159,
       60,   61,   60,  335,   84,   61,  274,  161,   60,   60,
       60,   60,  335,   61,   61,   60,   60,   60,   60,  335,
       61,   61,  276,  335,   60,  275,   60,  335,  335,   61,
      278,  335,   60,  280,   60,  335,  281,   61,  292,   60,
      277,   60,  335,  335,   61,   84,   60,   60,   60,   60,
      335,   61,   61,  335,   84,  291,   60,  335,   60,  335,

      282,   61,  284,   60,  293,   60,  335,   60,   61,   60,
      335,   60,   61,   60,  335,   60,   61,   60,  335,   60,
       61,   60,  335,   60,   61,   60,  335,  335,   61,   60,
      335,   60,  294,  158,   61,  158,  335,  335,  305,  159,
      335,  295,  335,  335,   60,  168,   60,  161,  298,   61,
      335,   60,   84,   60,  335,   60,   61,   60,  335,   60,
       61,   60,  335,  335,   61,  158,  335,  158,   84,  335,
      335,  159,  307,   60,  306,   60,  335,  315,   61,  161,
      335,   60,  309,   60,  335,   60,   61,   60,  335,   84,
       61,  335,  335,  310,   60,  335,   60,  316,  335,   61,

       60,  158,   60,  158,   60,   61,   60,  159,   60,   61,
       60,  335,  323,   61,  317,  161,  158,  335,  158,  319,
      335,   60,  159,   60,  335,  335,   61,  320,  335,   60,
      161,   60,  335,  335,   61,  324,  168,   60,  335,   60,
      335,  335,   61,  335,  335,   84,  326,  335,   84,  335,
      335,  335,  335,  329,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  331,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  333,
      335,  335,  335,  335,  335,  335,   84,   47,   47,   47,

       47,   47,   47,   62,  335,   62,  335,   62,  107,  107,
      335,  107,  107,  107,  144,  144,  335,  144,  144,  144,
      160,  335,  335,  160,  160,    3,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335

    } ;

static const flex_int16_t yy_chk[1498] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    7,    5,   10,   13,   10,   10,   11,   11,
       13,   11,   11,   12,  339,   12,   12,   14,  334,   14,
       14,   15,  332,   15,   15,   20,   46,   20,   46,   21,

       20,   21,   50,   50,   21,   22,    7,   22,   47,   23,
       22,   23,  330,   24,   23,   24,  328,   25,   24,   25,
      327,   26,   25,   26,  322,   20,   26,   27,   21,   27,
       22,   28,   27,   28,  321,   29,   28,   29,   23,   30,
       29,   30,   47,  318,   30,   25,   55,   55,  314,   27,
       26,   31,  313,   31,   26,  312,   31,   32,   51,   32,
       51,   51,   32,   28,  311,   33,   22,   33,  308,   34,
       33,   34,   27,   52,   34,   52,   52,  304,   35,   36,
       35,   36,   30,   35,   36,   56,   56,   37,  303,   37,
       29,   30,   37,   30,   38,   61,   38,   61,   30,   38,

       30,  302,   32,   31,  301,   39,   31,   39,  300,   31,
       39,   40,   32,   40,   34,  299,   40,   33,  296,   33,
       41,   42,   41,   42,   35,   41,   42,   34,   37,   33,
      290,   35,   35,   35,   36,  289,   43,   35,   43,  288,
       57,   43,   57,   57,   58,  287,   58,   58,   60,   38,
       60,  286,  106,   60,  106,  106,   40,   39,  285,   39,
       62,  279,   62,   39,  273,   62,   39,   63,   41,   63,
      270,   64,   63,   64,  269,   42,   64,   65,   66,   65,
       66,  268,   65,   66,   67,  109,   67,  109,   68,   67,
       68,   43,  267,   68,   69,   65,   69,   63,  266,   69,

       64,   70,  110,   70,  110,   71,   70,   71,  110,   72,
       71,   72,  265,   73,   72,   73,  110,   67,   73,  264,
       68,  261,   69,   71,   74,   75,   74,   75,   70,   74,
       75,  257,   76,   77,   76,   77,   66,   76,   77,   78,
       79,   78,   79,   73,   78,   79,   80,  143,   80,  143,
       81,   80,   81,  249,   82,   81,   82,  243,   83,   82,
       83,  242,   84,   83,   84,  108,  108,   84,   72,   85,
       86,   85,   86,   74,   85,   86,  241,   77,  240,  239,
       87,   76,   87,   75,   88,   87,   88,   80,   89,   88,
       89,  238,   90,   89,   90,  237,  233,   90,   78,   82,

       79,  143,   91,   81,   91,  228,   93,   91,   93,  214,
       95,   93,   95,  204,   86,   95,  203,   83,   96,   97,
       96,   97,  202,   96,   97,   88,  201,  200,   85,   86,
       99,  158,   99,  158,  199,   99,   94,  158,   94,  198,
       87,   94,   98,   89,   98,  158,   93,   98,   90,  100,
       91,  100,  192,  101,  100,  101,  187,  103,  101,  103,
      157,   95,  103,   97,   91,   92,   92,  141,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   96,   94,
       92,   92,   92,   92,  102,   98,  102,  105,  104,  102,
      104,   94,   49,  104,  111,   44,  111,  101,   19,  111,

       17,   16,   92,   92,   92,   92,    3,    0,    0,  100,
      101,  112,  111,  112,    0,    0,  112,  103,  113,  114,
      113,  114,    0,  113,  114,  115,  118,  115,  118,  102,
      115,  118,   92,   92,   92,   92,    0,  116,  112,  116,
        0,    0,  116,    0,  115,  117,  104,  117,  113,  119,
      117,  119,    0,  118,  119,  120,  121,  120,  121,  116,
      120,  121,    0,  122,  123,  122,  123,  117,  122,  123,
      124,    0,  124,    0,    0,  124,  119,  114,  125,  126,
      125,  126,  121,  125,  126,  127,  128,  127,  128,    0,
      127,  128,  129,  130,  129,  130,    0,  129,  130,  131,

      133,  131,  133,    0,  131,  133,    0,  122,  132,    0,
      132,  124,  134,  132,  134,    0,  120,  134,  135,  123,
      135,    0,  136,  135,  136,    0,    0,  136,  126,    0,
      137,    0,  137,  127,  130,  137,  138,  160,  138,  160,
        0,  138,  131,  160,  139,  128,  139,    0,  129,  139,
      140,  160,  140,  132,  142,  140,  142,    0,    0,  142,
      144,    0,  144,  135,  145,  144,  145,    0,    0,  145,
      146,    0,  146,  134,  147,  146,  147,    0,  197,  147,
      197,    0,  136,  137,  197,    0,    0,    0,  138,  139,
      148,  140,  148,    0,  149,  148,  149,    0,  150,  149,

      150,    0,  151,  150,  151,    0,    0,  151,  142,  145,
      152,  146,  152,    0,  144,  152,  153,  154,  153,  154,
        0,  153,  154,  155,  156,  155,  156,    0,  155,  156,
      147,  161,  161,  161,    0,  148,  163,    0,  163,  149,
      162,  163,  162,  150,    0,  162,    0,  151,    0,  161,
      161,  161,  161,    0,  165,  152,  165,  161,  163,  165,
        0,  161,  161,  164,  166,  164,  166,    0,  164,  166,
        0,  154,  155,    0,  167,  162,  167,  153,  168,  167,
      168,  164,  169,  168,  169,    0,    0,  169,  170,    0,
      170,  166,  171,  170,  171,    0,    0,  171,  167,  165,

      172,  173,  172,  173,    0,  172,  173,  174,  175,  174,
      175,    0,  174,  175,    0,  176,  170,  176,    0,  177,
      176,  177,    0,  178,  177,  178,    0,  179,  178,  179,
        0,  180,  179,  180,  169,  181,  180,  181,    0,    0,
      181,  182,  183,  182,  183,    0,  182,  183,  184,    0,
      184,  171,    0,  184,  174,    0,    0,    0,    0,  172,
      177,  173,  185,  175,  185,    0,  186,  185,  186,    0,
      188,  186,  188,  189,  176,  189,  188,  190,  189,  190,
      180,    0,  190,  178,  188,  179,  191,  193,  191,  193,
        0,  191,  193,  181,  194,  182,  194,  184,    0,  194,

      195,    0,  195,  183,  205,  195,  205,    0,  208,  205,
      208,    0,    0,  208,  206,  188,  206,    0,  189,  206,
      185,    0,    0,    0,  186,    0,  205,  196,  196,  196,
      190,    0,  206,  193,  207,  211,  207,  211,  191,  207,
      211,    0,    0,  194,    0,  196,  196,  196,  196,  236,
        0,  236,  195,  196,  207,  236,    0,  196,  196,  209,
        0,  209,  208,  210,  209,  210,    0,  212,  210,  212,
        0,  213,  212,  213,    0,  215,  213,  215,    0,    0,
      215,  209,  216,    0,  216,  210,    0,  216,  217,    0,
      217,  212,  218,  217,  218,  211,  219,  218,  219,    0,

      220,  219,  220,    0,    0,  220,  221,  229,  221,  229,
      222,  221,  222,  229,  223,  222,  223,    0,  224,  223,
      224,  229,  225,  224,  225,    0,  226,  225,  226,  215,
      213,  226,  227,  230,  227,  230,    0,  227,  230,    0,
      216,  219,  231,  232,  231,  232,    0,  231,  232,  220,
      218,  234,  221,  234,    0,  222,  234,  235,  223,  235,
        0,  244,  235,  244,    0,    0,  244,  225,    0,  245,
      229,  245,    0,    0,  245,  226,  224,    0,  246,    0,
      246,  227,  244,  246,  247,  280,  247,  280,  248,  247,
      248,  280,    0,  248,    0,    0,  230,  245,  231,  280,

      234,  250,  251,  250,  251,    0,  250,  251,    0,  252,
      246,  252,    0,    0,  252,  235,    0,  253,  248,  253,
        0,  254,  253,  254,    0,  255,  254,  255,    0,  256,
      255,  256,    0,  258,  256,  258,  259,  280,  259,  258,
      260,  259,  260,    0,  247,  260,  250,  258,  262,  263,
      262,  263,    0,  262,  263,  271,  272,  271,  272,    0,
      271,  272,  253,    0,  274,  252,  274,    0,    0,  274,
      256,    0,  275,  258,  275,    0,  259,  275,  272,  276,
      254,  276,    0,    0,  276,  255,  277,  278,  277,  278,
        0,  277,  278,    0,  263,  271,  281,    0,  281,    0,

      260,  281,  262,  282,  274,  282,    0,  284,  282,  284,
        0,  291,  284,  291,    0,  292,  291,  292,    0,  293,
      292,  293,    0,  294,  293,  294,    0,    0,  294,  295,
        0,  295,  275,  297,  295,  297,    0,    0,  291,  297,
        0,  278,    0,    0,  298,  292,  298,  297,  281,  298,
        0,  305,  284,  305,    0,  306,  305,  306,    0,  307,
      306,  307,    0,    0,  307,  309,    0,  309,  282,    0,
        0,  309,  294,  310,  293,  310,    0,  305,  310,  309,
        0,  315,  297,  315,    0,  316,  315,  316,    0,  295,
      316,    0,    0,  298,  317,    0,  317,  306,    0,  317,

      320,  319,  320,  319,  323,  320,  323,  319,  324,  323,
      324,    0,  315,  324,  307,  319,  326,    0,  326,  309,
        0,  329,  326,  329,    0,    0,  329,  310,    0,  331,
      326,  331,    0,    0,  331,  316,  323,  333,    0,  333,
        0,    0,  333,    0,    0,  320,  319,    0,  317,    0,
        0,    0,    0,  324,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  329,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  331,
        0,    0,    0,    0,    0,    0,  333,  336,  336,  336,

      336,  336,  336,  337,    0,  337,    0,  337,  338,  338,
        0,  338,  338,  338,  340,  340,    0,  340,  340,  340,
      341,    0,    0,  341,  341,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 3 "lex.l"
	#include <string.h>
	#include <stdlib.h>
	#include "uthash.h"
	#include "parser.tab.h"

	typedef struct {
		int line_no;
		int col_no;
		char type[100];
	} Content;

	typedef struct token{
		char val[100];      /* Key */
		Content* content;
		UT_hash_handle hh;
	} Lexeme;

	void addHashUtil(char* yytext, char* type, int line, int col);
	void addHash(char* type, int line_no, char* value, int col_no);
	Lexeme* findHash(char* str);
	/* void printHash();
	void printLines(); */

	Lexeme* lexemes = NULL;  /* hash array */
	int line=1, col=1;
#line 915 "lex.yy.c"
#line 916 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 53 "lex.l"


#line 1136 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 336 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1426 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 55 "lex.l"
{yylval = line; return CLASS;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 57 "lex.l"
{yylval = line; return CREATE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 59 "lex.l"
{yylval = line; return END;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 61 "lex.l"
{yylval = line; return FEATURE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "lex.l"
{
						// printf("%s\n", yytext);
						addHashUtil(yytext, "Keyword", line, col);
						col += yyleng;
						/* return KEYWORD; */
					}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 69 "lex.l"
{
						// printf("%s\n", yytext);
						addHashUtil(yytext, "Predefined Type", line, col);
						col += yyleng;
						return DATATYPE;
					}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 75 "lex.l"
{
						// printf("%s\n", yytext);
						strtok(yytext, "(");
						addHashUtil(yytext, "Function", line, col);
						col += yyleng;
						/* return FUNCTION; */
					}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 82 "lex.l"
{
						// printf("%s\n", yytext);
						addHashUtil(yytext, "Special Operator", line, col);
						col += yyleng;
					}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 87 "lex.l"
{
						// printf("%s\n", yytext);
						addHashUtil(yytext, "Identifier", line, col);
						col += yyleng;
						yylval = line;
						return IDENTIFIER;
					}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 94 "lex.l"
{
						// printf("%s\n", yytext);
						addHashUtil(yytext, "Integer", line, col);
						col += yyleng;
						yylval = line;
						return INTEGER;
					}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 101 "lex.l"
{
						// printf("%s\n", yytext);
						addHashUtil(yytext, "Real No.", line, col);
						col += yyleng;
						yylval = line;
						return REAL;
					}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 108 "lex.l"
{
						// printf("%s\n", yytext);
						addHashUtil(yytext, "String", line, col);
						col += yyleng;
						yylval = line;
						return STRING;
					}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "lex.l"
{
						col += yyleng;
					}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 118 "lex.l"
{
						line++;
						col=1;
					}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 122 "lex.l"
{
						col += yyleng;
					}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 125 "lex.l"
{
						// printf("%s\n", yytext);
						addHashUtil(yytext, "Operator", line, col);
						col += yyleng;
					}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 130 "lex.l"
{
						// printf("%s\n", yytext);
						addHashUtil(yytext, "Comment", line, col);
						col += yyleng;
					}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 135 "lex.l"
{
						col += yyleng;
					}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 138 "lex.l"
{
							return COLON;
					}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 141 "lex.l"
ECHO;
	YY_BREAK
#line 1359 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 336 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 336 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 335);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 141 "lex.l"


void addHashUtil(char* yytext, char* type, int line, int col) {
    Lexeme* temp = (Lexeme*)malloc(sizeof(Lexeme));
    temp = findHash(yytext);
    if(temp == NULL)
        addHash(type, line, yytext, col);
}

void addHash(char* type, int line_no, char* value, int col_no) {
    Lexeme* temp = (Lexeme*)malloc(sizeof(Lexeme));
    strcpy(temp->val, value);
    temp->content = (Content*)malloc(sizeof(Content));
    temp->content->line_no = line_no;
    temp->content->col_no = col_no;
    strcpy(temp->content->type, type);
    HASH_ADD_KEYPTR(hh, lexemes, temp->val, strlen(temp->val), temp);
    /* printf("%10s|%10d\t|\t%5d\t|\t%-50s\t|\t%-20s|\n"," ", line, col, yytext, type); */
    /* printLines(); */
    free(temp);
}

Lexeme* findHash(char* str) {
    Lexeme* temp = (Lexeme*)malloc(sizeof(Lexeme));
    HASH_FIND_STR(lexemes, str, temp);
    return temp;
}

